### ISSUE TITLE
黑色配色下，文字是灰色。完全看不清

### ISSUE THREAD

**Issue by chendabai** [zyuyou/intellij-translation#2]
黑色配色下，文字是灰色。完全看不清
![qq 20160706115133](https://cloud.githubusercontent.com/assets/10323801/16607136/7658d632-4370-11e6-9229-bc8f21986c5d.png)

**Comment by zyuyou** [comment]
@anzhidabai 修改了下样式，已经可以啦。从IDEA仓库更新一下。
