### ISSUE TITLE
IDEA 2016.2 不能使用问题

### ISSUE THREAD

**Issue by zyuyou** [zyuyou/intellij-translation#5]
IDEA 2016.2 已经兼容处理，但是想跟 #3 一起发布。请耐心等待，我尽快处理完成。

**Comment by justmd5** [comment]
# 什么时候能修复呢？等着用呢。感谢！:)

**Comment by zyuyou** [comment]
@justmd5 已经暂时先发布了兼容版本。最近工作太忙，没时间做。

**Comment by YangZhang00** [comment]
您好，IDEA 201603 好像不能用了，是最新版本不兼容么

**Comment by zyuyou** [comment]
@SunLangzi 是的,最新版本不兼容了.  而且因为工作关系, 该仓库不再提供维护了.  这里推荐另外一个更好用的翻译插件 [YiiGuxing/TranslationPlugin](http://yiiguxing.github.io/TranslationPlugin/)  非常感谢你的使用.
